version: "3.3"
   
services:
  jupyter-hub:
    build:
      context: ./jupyter-hub
      dockerfile: ./Dockerfile_jupyter-hub
    container_name: jupyterhub
    image: jupyterhub
    networks: 
      - jupyterhub-network
    ports:
      - "80:8000"
      - "443:443"
      - "8080:8080"
    volumes:
      - "./notebooks:/notebooks"
      - "/efs:/efs"
      - "./jupyter-data:/data"
      - "/var/run/docker.sock:/var/run/docker.sock:rw"
    environment:
      aws_access_key_id: ${aws_access_key_id}
      aws_secret_access_key: ${aws_secret_access_key}
      hostname: ${hostname}

      # This username will be a JupyterHub admin
      JUPYTERHUB_ADMIN: admin
      # All containers will join this network
      DOCKER_NETWORK_NAME: jupyterhub-network
      # JupyterHub will spawn this Notebook image for users
      # TODO: make sure to build the custom image in jupyter-hub/
      # docker build -t minimal-notebook-xinyu .
      DOCKER_NOTEBOOK_IMAGE: minimal-notebook-xinyu
      # DOCKER_NOTEBOOK_IMAGE: jupyter/minimal-notebook:latest
      # Notebook directory inside user image
      DOCKER_NOTEBOOK_DIR: /home/jovyan/work
      # Using this run command
      DOCKER_SPAWN_CMD: start-singleuser.sh
    command: >
      jupyterhub -f /srv/jupyterhub/jupyterhub_config.py

networks:
  jupyterhub-network:
    name: jupyterhub-network
