# Copyright (c) Jupyter Development Team.
# Distributed under the terms of the Modified BSD License.
FROM jupyterhub/jupyterhub

# Install dockerspawner, nativeauthenticator
RUN python3 -m pip install --no-cache-dir \
        fargatespawner \
        jupyterhub-idle-culler \
        oauthenticator \
        jupyterhub-nativeauthenticator \
        matplotlib

COPY ./localhost.key /tmp/localhost.key
COPY ./localhost.crt /tmp/localhost.crt
COPY ./jupyterhub_config_aws.py /srv/jupyterhub/jupyterhub_config.py
# COPY ./jupyterhub_config.py /srv/jupyterhub/jupyterhub_config.py

CMD ["jupyterhub", "-f", "/srv/jupyterhub/jupyterhub_config.py"]