# Copyright (c) Jupyter Development Team.
# Distributed under the terms of the Modified BSD License.
FROM jupyter/minimal-notebook:latest

# Install dockerspawner, nativeauthenticator
RUN python3 -m pip install --no-cache-dir \
        matplotlib \
        numpy \
        astropy \
        jupyterlab-git
